# Generated by Django 3.0.6 on 2020-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.PositiveIntegerField(choices=[['Completed', 'Not Completed']]),
        ),
    ]
